version: "3.8"
services:
    # web:
    #     build: ./employee_project
    #     command: >
    #         sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    #     volumes:
    #         - ././employee_project/:/usr/src/app/
    #     ports:
    #         - 8000:8000
    #     # depends_on:
    #     #     - pg
    pg:
        container_name: pg_container
        image: postgres:13.2-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: employee_db
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "5432:5432"
        volumes:
            - ./data:/data
            - ./data/misc/django_init.sql:/docker-entrypoint-initdb.d/1-django-init.sql
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:5.2
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_LISTEN_PORT: 5433
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
        ports:
            - "5433:5433"
        depends_on:
            - pg